/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Controller;

/**
 *
 * @author kai
 */
public class mealsUI extends javax.swing.JPanel {

    /**
     * Creates new form meals
     */
    public mealsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        beefimg = new javax.swing.JLabel();
        mangoimg = new javax.swing.JLabel();
        porkimg = new javax.swing.JLabel();
        mochaimg = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chickenimg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        milkteaimg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        porknu = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        beefnu1 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        chickennu = new javax.swing.JSpinner();
        mochannu = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        milkteanu = new javax.swing.JSpinner();
        mangonu = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 3600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(216, 154, 158));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        beefimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/beef.png"))); // NOI18N
        jPanel1.add(beefimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        mangoimg.setForeground(new java.awt.Color(230, 217, 184));
        mangoimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mango.png"))); // NOI18N
        jPanel1.add(mangoimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2940, -1, -1));

        porkimg.setForeground(new java.awt.Color(230, 217, 184));
        porkimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pork.png"))); // NOI18N
        jPanel1.add(porkimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, -1, -1));

        mochaimg.setForeground(new java.awt.Color(230, 217, 184));
        mochaimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mocha.png"))); // NOI18N
        jPanel1.add(mochaimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1560, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(230, 217, 184));
        jLabel12.setText("抹茶鬆餅  $250");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1520, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 217, 184));
        jLabel3.setText("芒果鬆餅  $220");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 2900, -1, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(230, 217, 184));
        jLabel14.setText("泰奶鬆餅  $220");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 2220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 48)); // NOI18N
        jLabel9.setText("鬆餅");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1480, 120, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 217, 184));
        jLabel8.setText("蒜酥雞腿排佐鮮蝦  $350");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 1020, -1, -1));

        chickenimg.setForeground(new java.awt.Color(230, 217, 184));
        chickenimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chicken.png"))); // NOI18N
        jPanel1.add(chickenimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1060, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 217, 184));
        jLabel6.setText("戰斧豬排佐鮮蔬  $400");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(230, 217, 184));
        jLabel4.setText("帶骨牛小排佐鮮蝦  $480");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        milkteaimg.setForeground(new java.awt.Color(230, 217, 184));
        milkteaimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/milktea.png"))); // NOI18N
        jPanel1.add(milkteaimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 48)); // NOI18N
        jLabel1.setText("主餐");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        porknu.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jPanel1.add(porknu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 760, 80, 60));

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("數量");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 720, -1, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("數量");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        beefnu1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jPanel1.add(beefnu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 80, 60));

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 153));
        jLabel17.setText("數量");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1200, -1, -1));

        chickennu.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jPanel1.add(chickennu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1240, 80, 60));

        mochannu.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jPanel1.add(mochannu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1800, 80, 60));

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 153));
        jLabel18.setText("數量");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1760, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("數量");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 2490, -1, -1));

        milkteanu.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jPanel1.add(milkteanu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 2530, 80, 60));

        mangonu.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jPanel1.add(mangonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 3190, 80, 60));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("數量");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 3150, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 3540));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beefimg;
    private javax.swing.JSpinner beefnu1;
    private javax.swing.JLabel chickenimg;
    private javax.swing.JSpinner chickennu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mangoimg;
    private javax.swing.JSpinner mangonu;
    private javax.swing.JLabel milkteaimg;
    private javax.swing.JSpinner milkteanu;
    private javax.swing.JLabel mochaimg;
    private javax.swing.JSpinner mochannu;
    private javax.swing.JLabel porkimg;
    private javax.swing.JSpinner porknu;
    // End of variables declaration//GEN-END:variables
}
